# Generated by Django 4.2.19 on 2025-02-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.EmailField(max_length=254)),    
                ('email', models.EmailField(max_length=254)),
            ],  
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
