# Generated by Django 4.2.19 on 2025-02-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_aluno_delete_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
